OBJECTS = tfilt.o	tparse.o	util.o	table.o

all:       	     tfilt.exe

tfilt.exe:	          $(OBJECTS)
	gcc -o tfilt.exe $(OBJECTS)

tfilt.o:	tfilt.c	table.h	token.h

tparse.o:	tparse.c	table.h	token.h

util.o:		util.c	table.h	token.h

table.o:	table.c	table.h

clean:
		rm -f $(OBJECTS) core tfilt

